spring.application.name=backend

# PostgreSQL (comentado)
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/game_list}
# spring.datasource.driver-class-name=org.postgresql.Driver

# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/game_list}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.jackson.serialization.indent_output=true

access.token=${ACCESS_TOKEN}
client.id=${CLIENT_ID}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS}